### ISSUE TITLE
Vinegar fails to build on 32-bit CPUs

### ISSUE THREAD

**Issue by xenanthropy** [vinegarhq/vinegar#325]
#### Describe the bug
- [X] I have searched open and closed issues to make sure that the bug has not yet been reported
- [X] I have read the [minimum requirements](https://vinegarhq.org/Requirements/index.html).

#### To Reproduce
Build vinegar with 32-bit cpu

attempting to build with either `make` or `go build ./cmd/vinegar` results in:
```shell
# github.com/vinegarhq/vinegar/sysinfo
sysinfo/sysinfo.go:11:12: undefined: Processor
sysinfo/sysinfo.go:19:8: undefined: getCPU
```

**Comment by reflexran** [comment]
I don't think you read the minimum requirements? It clearly says that you need a X86-64 CPU

**Comment by apprehensions** [comment]
Vinegar makes running Roblox easier on Linux, and a requirement of that is indeed a amd64 processor. This issue is related to the `sysinfo` package of Vinegar, which is only used for retrieving system information, and in return this is a bug as a feature.

While this will be fixed soon, i will see if it is possible to introduce a compiler warning requirement.
