### ISSUE TITLE
Thinks valid wineroot path is not valid, despite all flatpak permissions allowing it.

### ISSUE THREAD

**Issue by tjhexf** [vinegarhq/vinegar#327]
#### Describe the bug
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported
- [x] I have read the [minimum requirements](https://vinegarhq.org/Requirements/index.html).

Vinegar's exec seems to not be able to access the wineroot.
Allowing it through flatseal does make the vinegar edit command find the path, but weirdly enough running anything through vinegar player or exec still thinks the wine path supplied does not exist, when it does and ive verified flatpak permissions.

#### To Reproduce
add a different wineroot under config
attempt to run

### Logs
2024/01/01 16:01:06 deployment.go:41: Fetching latest version of WindowsPlayer for channel LIVE
2024/01/01 16:01:07 deployment.go:48: Fetched WindowsPlayer canonical version 0.605.3.6050660
2024/01/01 16:01:07 binary.go:281: WindowsPlayer is up to date (version-48a28da848b7420d)
2024/01/01 16:01:07 binary.go:286: Using Renderer: D3D11
2024/01/01 16:01:07 fflags.go:34: Applying custom FFlags: /home/jho/.var/app/org.vinegarhq.Vinegar/data/vinegar/prefix/vinegar/versions/version-48a28da848b7420d/ClientSettings/ClientAppSettings.json
2024/01/01 16:01:07 dxvk.go:24: Enabling WINE DXVK DLL overrides
2024/01/01 16:01:07 discordrpc.go:16: Connecting to Discord RPC
2024/01/01 16:01:07 binary.go:100: WARNING: Could not initialize Discord RPC: drpc: discord is not running, disabling...
2024/01/01 16:01:07 binary.go:140: Launching WindowsPlayer (/home/jho/wine-ge/bin/wine /home/jho/.var/app/org.vinegarhq.Vinegar/data/vinegar/prefix/vinegar/versions/version-48a28da848b7420d/RobloxPlayerBeta.exe -app)
2024/01/01 16:01:07 vinegar.go:219: roblox process: fork/exec /home/jho/wine-ge/bin/wine: no such file or directory
2024/01/01 16:01:07 splash.go:189: Opening log file: /home/jho/.var/app/org.vinegarhq.Vinegar/cache/vinegar/logs/Player-2024-01-01T16:01:06-03:00.log

### System information
Thinkpad L14

* Installation method:

Cannot run the command, it again thinks wine-ge does not exist, when it does.

**Comment by tjhexf** [comment]
deleting the custom wineroot value in the config, then doing:
flatpak run org.vinegarhq.Vinegar exec explorer

Opens the system wine file manager, showing that the path to wine-ge does exist and binaries are there.

However, switching the wineroot config back to this existing path (vinegar edit does not complain, when home permissions are disabled it does.), makes it so vinegar exec explorer complains that it cant find wine-ge.

**Comment by apprehensions** [comment]
Thanks for reporting!

**Comment by mxhal** [comment]
send config, and dont use global flags

**Comment by lunarlettuce** [comment]
Ah, I know why this is occurring. We recently removed 32bit support from the Flatpak (seeing as there is no purpose in having it). This means that the error
`2024/01/01 16:01:07 vinegar.go:219: roblox process: fork/exec /home/jho/wine-ge/bin/wine: no such file or directory`  
does not indicate a sandboxing issue, but rather than you are trying to run an executable in an architecture different from what is permitted in Flatpak (i.e. 32 Bit wine). 

To remedy this issue, symlink wine64 to wine, and then point the sandbox to the symlinked file.

**Comment by lunarlettuce** [comment]
Actually, to correct myself, you will not even have to symlink the file. You should be able to simply point wineroot to wine64.

**Comment by RushingAlien** [comment]
@lunarlettuce 
Hello, seeing as you guys removed 32 bit support it would be best to execute wine64 instead of wine
Cause without 32 bit compat, most wine builds cannot start when you run it with wine instead of wine64
I use wine-proton-ge via the wineroot variable in config.toml, it ceases to work due to this

**Comment by RushingAlien** [comment]
> You should be able to simply point wineroot to wine64.

oh mb
