### ISSUE TITLE
version-9b68669a3b644e31 no longer working

### ISSUE THREAD

**Issue by mrfiguy** [vinegarhq/vinegar#468]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

The previous working version, 9b68669a3b644e31 is now outdated (for me), and seems that no other version so far is working. There is no error output.
![bucktoothemoji](https://github.com/user-attachments/assets/bef2d1cf-d7df-4f8f-9375-26d27e3dd62c)

### System information

```shell
* Vinegar: v1.7.7 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: AMD Custom APU 0405
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.5.0-valve22-1-neptune-65-g9a338ed8a75e
* Wine (Player): wine-9.18 (Staging)
* Wine (Studio): wine-9.18 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: amdgpu 0000:04:00.0 /sys/class/drm/card0
```

**Comment by WTlynx** [comment]
Vinegar has fallen. Many must dualboot

**Comment by apprehensions** [comment]
oh hell naw

**Comment by safariragoli2** [comment]
can confirm, was working yesterday but today loading with umu launcher gets stuck on splash screen
```bash
* Vinegar: v1.7.7
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.11.9-arch1-1
* Wine (Player): wine-9.18 (Staging)
* Wine (Studio): wine-9.18 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: nvidia 0000:01:00.0 /sys/class/drm/card1
  ```

**Comment by LoveAlexx** [comment]
Same issue it gets stuck on the loading screen, yet it worked just yesterday

**Comment by godzzo** [comment]
![image](https://github.com/user-attachments/assets/c2c4d497-60e8-4ef0-8c6d-fcdd7fae3ed5)

Under the Splash there is a MessageBox...

**Comment by Breegis** [comment]
I'm Also having this issue. Studio Worked for me on December 6th, but Doesn't work today. 
And considering we've been having to use a forced version for a certain amount of time since they stopped updating studio on vinegar for a while, and how no other version works, this might be the end. 

Unless running studio on wine and using grapejuice (which is dead at the moment) suddenly works, then studio is dead on linux rn. 

I wish there was a way to update studio in the same way that you can update Sober, using "flatpak update", where it immediately gets the newest version. 

It seems like they are focusing more on Sober than studio, which is another Roblox application that needs just as much love as the Roblox Client.

**Comment by Breegis** [comment]
There's a Fix, removing the ForcedVersion makes it work. Just remove that and update vinegar.
