### ISSUE TITLE
Roblox Studio crashes on startup

### ISSUE THREAD

**Issue by Splatert** [vinegarhq/vinegar#74]
Not sure if Studio was also affected by Roblox rolling out the wine-blocking anticheat but I cannot even launch it. It crashes on the splash screen.

Distro: Linux Mint
Wine version: wine-8.0.2
Installation method: Flatpak

Steps to reproduce the issue:
1. Install flatpak
2. launch Roblox Studio (vinegar)

![image](https://github.com/vinegarhq/vinegar/assets/82643571/8afe205f-06ae-4388-aef2-910ba09498ae)

The error I get:
[https://pastebin.com/raw/chu4gEqy](url)

**Comment by Splatert** [comment]
The Flatpak installation didn't seem to come with a config file so I made one manually and unfortunately, trying all the renderer options didn't solve the issue with the crashing.

**Comment by apprehensions** [comment]
I do believe that this could be because of a bug in Vinegar where it is not using the 64-bit version of Studio, are you able to install the latest versions of Vinegar from git source directly to test this?

**Comment by Splatert** [comment]
Looking back again, it seems that only Roblox Player works fine.

**Comment by mr-sihc** [comment]
as if not, that is what was said

**Comment by apprehensions** [comment]
For anyone facing specific issues with Roblox, do make sure to use latest versions of Wine, such as Wine 8.13 or Wine GE.

**Comment by AvoMC** [comment]
This is fixed in the newer versions of Roblox Studio.
Please use wine-ge-custom latest version and reinstall Roblox Studio to never deal with this issue again.

**Comment by Splatert** [comment]
Seems that Studio does not crash on OpenGL (using Wine-GE) though the performance is a little slow. Especially when you want to test your games out.

**Comment by AvoMC** [comment]
Ok. so what I said before is kind of true.. let me explain.

Basically if you use wine 8.2 or newer, there is a bug with DXVK that causes Roblox Studio to crash at random instances. And, the main fix is to disable DXVK, but its not that easy because 25% to 50% of the Graphics is going to be glitched or not loading properly.

e.g - The fonts in the start page is bugged out
e.g - The warning for many settings won't be rendered properly.

And to fix all of that? You need DXVK. But like I said, but DXVK in wine 8.2 or newer isn't working properly and has a huge impact on Roblox Studio running.

Kind of a hit or miss situation, We will have to see what happens in the newers versions of Wine.

**Comment by Thelolguy1** [comment]
Solved by latest flatpak.

If you are not on the flatpak, ensure that you have childwindow patched wine, a dpi of 192 in winecfg, and a renderer set to Vulkan or D3D11 with DXVK.
