### ISSUE TITLE
[Feature Request] Configuration option to make vinegar download gplasync versions of dxvk

### ISSUE THREAD

**Issue by Username404-59** [vinegarhq/vinegar#77]
gplasync is a patch for dxvk which adds async compilation of shaders
Its features can be enabled with the DXVK_ASYNC=1 and DXVK_GPLASYNCCACHE=1 environment variables

Builds of it are available at https://gitlab.com/Ph42oN/dxvk-gplasync/-/tree/main/releases?ref_type=heads

**Comment by apprehensions** [comment]
The way this project does it is via tarballs directly on the git tree, this method is incompatible with current Vinegar; Please ask that upstream fork to use releases instead of tarballs on the git tree, they exist as a feature on modern Git hosting services.

**Comment by Username404-59** [comment]
There are releases on gitlab too: https://gitlab.com/Ph42oN/dxvk-gplasync/-/releases

**Comment by apprehensions** [comment]
theres unfortunately no good way to implement this other than using different urls; which can't work for multiple versions or cached DXVK tarballs that are re-used for downloads, since we use the variable of the dxvk version instead of a direct url to save the tarballs.

Only thing to do at this stage is disable DXVK for vinegar itself and install the DXVK forks by hand using the included `setup_dxvk.sh` script leading to Vinegar's wineprefix.
